apiVersion: example.suleyman.io/v1alpha1
kind: AppDefinition
metadata:
  name: sample-app
  namespace: default
spec:
  image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest
  requestsCpu: "250m"
  requestsMemory: "512Mi"
  limitsCpu: "250m"
  limitsMemory: "1Gi"

  env:
    - name: THEIA_CUSTOM_MESSAGE
      value: "Hello from AppDefinition"
    - name: WORKSPACE_OWNER
      value: "bartu"

