apiVersion: example.suleyman.io/v1
kind: AppDefinition
metadata:
  name: sample-app
  namespace: default
spec:
  name: sample-app
  image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest
  port: 3000
  uid: 101
  ingressname: sample-app
  minInstances: 1
  maxInstances: 1
  requestsCpu: 250m
  requestsMemory: 512Mi
  limitsCpu: 250m
  limitsMemory: 1Gi
  downlinkLimit: 2000
  uplinkLimit: 1000
  monitor:
    port: 9000
    activityTracker:
      timeoutAfter: 1800
      notifyAfter: 600
