apiVersion: example.suleyman.io/v1
kind: AppDefinition
metadata:
  name: sample-app
  namespace: default
spec:
  name: sample-app
  image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest  # keep blueprint for local
  imagePullPolicy: IfNotPresent
  pullSecret: regcred
  ingressname: sample-app
  uid: 101
  port: 3000
  minInstances: 0
  maxInstances: 50
  timeout: 180
  requestsCpu: 100m
  requestsMemory: 1000Mi
  limitsCpu: "2"
  limitsMemory: 1200Mi
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: /home/henkan/project
