apiVersion: example.suleyman.io/v1
kind: Session
metadata:
  name: demo-session-uid
  namespace: default
spec:
  name: demo-session-uid
  workspace: demo-ws
  appDefinition: sample-app
  user: bartu
  sessionSecret: super-secret-456
