apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.example.suleyman.io
spec:
  group: example.suleyman.io
  scope: Namespaced
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
    shortNames:
      - sess
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Logical session name (Theia-style)
                name:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'

                # Workspace this session belongs to
                workspace:
                  type: string

                # Cached from workspace (AppDefinition name)
                appDefinition:
                  type: string
                  pattern: '^[a-z0-9A-Z-_]+$'

                # Cached from workspace
                user:
                  type: string

                # Optional reference to some secret for the session
                sessionSecret:
                  type: string

                # Arbitrary options, int-or-string just like Theia Cloud
                options:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true

                # Extra env vars
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true

                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string

                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
              required:
                - name
                - user
                - appDefinition
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                url:
                  type: string
                error:
                  type: string
                lastActivity:
                  type: integer
          required:
            - spec
