apiVersion: example.suleyman.io/v1
kind: Session
metadata:
  name: demo-session-2
  namespace: default
spec:
  name: demo-session-2
  user: bartu                  # same user
  workspace: demo-ws-2         # different workspace
  appDefinition: sample-app
