apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  name: demo-ws
  namespace: default
spec:
  owner: "bartu"
  appDefinitionName: "sample-app"
  label: "Bartu demo workspace"
  storageSize: "5Gi"
  storageClassName: "hostpath"
  retainOnDelete: false
