apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  name: demo-ws
  namespace: default
spec:
  name: "demo-ws"
  label: "bartu-demo-workspace"
  appDefinition: "sample-app"
  user: "bartu"
  storage: "5Gi"
  options:
    some-flag: "true"
    max-idle-minutes: "60"
