apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  name: demo-ws-2
  namespace: default
spec:
  name: "demo-ws-2"
  label: "bartu-demo-workspace-2"
  storage: "workspace-demo-ws-2"   # PVC name
  appDefinition: "sample-app"
  user: "bartu"