apiVersion: example.suleyman.io/v1alpha1
kind: Workspace
metadata:
  name: demo-ws
  namespace: default
spec:
  owner: "bartu"
  appDefinitionName: "sample-app"
  label: "Bartu demo workspace" # (just a human-friendly name)
  storageSize: "5Gi"
  storageClassName: "hostpath"
