apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  name: demo-ws-2
  namespace: default
spec:
  name: demo-ws-2
  label: Bartu second workspace
  appDefinition: sample-app
  storage: 5Gi
  user: bartu
