apiVersion: theia.cloud/v1beta8
kind: Session
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"theia.cloud/v1beta8","kind":"Session","metadata":{"annotations":{},"labels":{"app.henkan.io/henkanProjectName":"bartu-demo-workspace","app.henkan.io/workspaceName":"demo-ws","app.henkan.io/workspaceUser":"bartu"},"name":"bartu-demo-ws","namespace":"default"},"spec":{"appDefinition":"henkan-designer","envVars":{"COMMIT_GENAI_ENDPOINT":"https://example.com/webhook/xyz","EMAIL":"bartu.kacar@globalmaksimum.com","GIT_AUTHOR_NAME":"bartu405","GIT_SSL_NO_VERIFY":"true","HENKAN_GIT_EMAIL":"bartu.kacar@globalmaksimum.com","HENKAN_GIT_USER":"bartu","HENKAN_META_API_URL":"http://henkan-metaapi.henkan-metaapi","HENKAN_PROJECT_GIT_URL":"https://github.com/GlobalMaksimum/henkan-etl-flow-project.git","HENKAN_PROJECT_NAME":"busra"},"name":"bartu-demo-ws","sessionSecret":"henkansecret","user":"bartu","workspace":"bartu-demo-ws"}}
  creationTimestamp: "2026-01-12T11:52:35Z"
  finalizers:
    - sessions.theia.cloud/finalizer
  generation: 1
  labels:
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
    - apiVersion: theia.cloud/v1beta5
      blockOwnerDeletion: true
      controller: true
      kind: Workspace
      name: bartu-demo-ws
      uid: cd5e9007-7f7c-48f6-b353-e6585688027a
  resourceVersion: "300419"
  uid: 95474d16-0681-4f99-9d65-30611b8f5917
spec:
  appDefinition: henkan-designer
  envVars:
    COMMIT_GENAI_ENDPOINT: https://example.com/webhook/xyz
    EMAIL: bartu.kacar@globalmaksimum.com
    GIT_AUTHOR_NAME: bartu405
    GIT_SSL_NO_VERIFY: "true"
    HENKAN_GIT_EMAIL: bartu.kacar@globalmaksimum.com
    HENKAN_GIT_USER: bartu
    HENKAN_META_API_URL: http://henkan-metaapi.henkan-metaapi
    HENKAN_PROJECT_GIT_URL: https://github.com/GlobalMaksimum/henkan-etl-flow-project.git
    HENKAN_PROJECT_NAME: busra
  name: bartu-demo-ws
  sessionSecret: henkansecret
  user: bartu
  workspace: bartu-demo-ws
status:
  lastActivity: 1768218755899
  operatorMessage: Session is running
  operatorStatus: HANDLED
  url: theia.localtest.me/95474d16-0681-4f99-9d65-30611b8f5917/