apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: "2025-12-04T12:26:30Z"
      name: default
      namespace: henkan-designer
      resourceVersion: "67781379"
      uid: faabd86f-4de3-4cb7-89cc-21d714fc179f
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: henkan-designer
        meta.helm.sh/release-namespace: henkan-designer
      creationTimestamp: "2025-12-04T12:26:36Z"
      labels:
        app.kubernetes.io/managed-by: Helm
      name: designer
      namespace: henkan-designer
      resourceVersion: "67781427"
      uid: 8bfdadda-361b-46e9-9d07-de202b96ec11
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: henkan-designer
        meta.helm.sh/release-namespace: henkan-designer
      creationTimestamp: "2025-12-04T12:26:36Z"
      labels:
        app.kubernetes.io/managed-by: Helm
      name: operator-api-service-account
      namespace: henkan-designer
      resourceVersion: "67781429"
      uid: cc59666a-904a-48ee-97b6-ccedbf9d724a
kind: List
metadata:
  resourceVersion: ""