apiVersion: theia.cloud/v1beta9
kind: AppDefinition
metadata:
  name: henkan-designer
  namespace: "{{ henkan_designer_namespace }}"
spec:
  name: henkan-designer
  image: "{{ internal_repo }}/globalmaksimum/theia-henkan:{{ henkan_designer_version }}"
  imagePullPolicy: IfNotPresent
  {% if dockerconfigjson is defined %}
  pullSecret: '{{ registry_pull_secret }}'
  {% endif %}
  uid: 101
  port: 3000
  ingressname: theia-cloud-demo-ws-ingress
  minInstances: 0
  maxInstances: 50
  timeout: 180
  requestsMemory: 1000M
  limitsMemory: 1200M
  requestsCpu: "100m"
  limitsCpu: "2"
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: "/home/henkan/project"