apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: henkan-designer
    meta.helm.sh/release-namespace: henkan-designer
  creationTimestamp: "2025-12-04T12:26:38Z"
  generation: 1
  labels:
    app: operator
    app.kubernetes.io/managed-by: Helm
  name: operator-deployment
  namespace: henkan-designer
  resourceVersion: "71090966"
  uid: f42c581c-90d1-4b25-a2b8-af47dd482283
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: operator
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --keycloak
            - --keycloakURL
            - https://keycloak.172.12.2.32.sslip.io/auth/
            - --keycloakRealm
            - henkan
            - --keycloakClientId
            - henkan-designer
            - --cloudProvider
            - K8S
            - --wondershaperImage
            - theiacloud/theia-cloud-wondershaper:0.11.0-next
            - --serviceUrl
            - https://<nil>
            - --sessionsPerUser
            - "3"
            - --appId
            - henkan
            - --instancesHost
            - designer.172.12.2.32.sslip.io
            - --storageClassName
            - local-path
            - --requestedStorage
            - 250Mi
            - --leaderLeaseDuration
            - "6"
            - --leaderRenewDeadline
            - "4"
            - --leaderRetryPeriod
            - "1"
            - --maxWatchIdleTime
            - "3600000"
            - --oAuth2ProxyVersion
            - henkan.azurecr.io/oauth2-proxy/oauth2-proxy:v7.5.1
          image: henkan.azurecr.io/globalmaksimum/theia-cloud-operator:6f47ad6
          imagePullPolicy: IfNotPresent
          name: operator-container
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: operator-api-service-account
      serviceAccountName: operator-api-service-account
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2025-12-04T12:26:38Z"
      lastUpdateTime: "2025-12-04T12:26:44Z"
      message: ReplicaSet "operator-deployment-759cc888b7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-12-08T23:14:36Z"
      lastUpdateTime: "2025-12-08T23:14:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1