apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: rke2025-01
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2025-12-09T01:45:04Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    theia-cloud.io/workspace-name: bartu-bartu-test
  name: ws-bartu-henkan-designer-e970b4e57ee4
  namespace: henkan-designer
  ownerReferences:
    - apiVersion: theia.cloud/v1beta5
      kind: Workspace
      name: bartu-bartu-test
      uid: 241495f0-d4f2-4d2e-a304-e970b4e57ee4
  resourceVersion: "71161185"
  uid: 46b66e87-2d47-42b2-ab2b-3ce22b948256
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-46b66e87-2d47-42b2-ab2b-3ce22b948256
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Mi
  phase: Bound