apiVersion: theia.cloud/v1beta8
kind: Session
metadata:
  creationTimestamp: "2025-12-09T01:48:47Z"
  generation: 1
  labels:
    app.henkan.io/henkanProjectName: busra
    app.henkan.io/workspaceName: bartu-test
    app.henkan.io/workspaceUser: bartu
  name: bartu-bartu-test
  namespace: henkan-designer
  resourceVersion: "71163044"
  uid: feb90431-7568-4da4-861e-8c29c58e895b
spec:
  appDefinition: henkan-designer
  envVars:
    COMMIT_GENAI_ENDPOINT: https://henkan-genai.172.12.2.32.sslip.io/webhook/6e201b9b-ca39-44d8-9600-70520911ea5c
    EMAIL: bartu@globalmaksimum.com
    GIT_AUTHOR_NAME: bartu
    GIT_SSL_NO_VERIFY: "true"
    HENKAN_GIT_EMAIL: bartu@globalmaksimum.com
    HENKAN_GIT_USER: bartu
    HENKAN_META_API_URL: http://henkan-metaapi.henkan-metaapi
    HENKAN_PROJECT_GIT_URL: https://github.com/GlobalMaksimum/henkan-etl-flow-project.git
    HENKAN_PROJECT_NAME: busra
  name: bartu-bartu-test
  sessionSecret: henkansecret
  user: bartu
  workspace: bartu-bartu-test
status:
  lastActivity: 1765244928209
  operatorStatus: HANDLED
  url: designer.172.12.2.32.sslip.io/feb90431-7568-4da4-861e-8c29c58e895b/