apiVersion: v1
data:
  authenticated-emails-list: bartu
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-18T12:55:58Z"
  labels:
    app.kubernetes.io/component: session
    app.kubernetes.io/part-of: theia-cloud
    theia-cloud.io/app-definition: henkan-designer
    theia-cloud.io/session: bartu-bartu-test
    theia-cloud.io/template-purpose: emails
    theia-cloud.io/user: bartu
  name: session-email-bartu-henkan-desi-5c863b669234
  namespace: henkan-designer
  ownerReferences:
    - apiVersion: theia.cloud/v1beta8
      kind: Session
      name: bartu-bartu-test
      uid: 697b8c28-4a27-4201-a80e-5c863b669234
  resourceVersion: "77349237"
  uid: 3eba6a97-1fb5-4d05-b6bd-4e04f9534429