# File: appdefinition-sample.yaml
apiVersion: theia.cloud/v1beta10
kind: AppDefinition
metadata:
  name: henkan-designer
  namespace: default
spec:
  name: henkan-designer
  image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest
  imagePullPolicy: IfNotPresent
  pullSecret: regcred
  ingressname: henkan-designer-ingress
  uid: 101
  port: 3000
  minInstances: 0
  maxInstances: 50
  timeout: 180
  requestsCpu: 100m
  requestsMemory: 1000Mi
  limitsCpu: "2"
  limitsMemory: 1200Mi
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: /home/henkan/project
