# File: oauth2-proxy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: default
data:
  oauth2-proxy.cfg: |
    provider="keycloak-oidc"
    redirect_url="http://placeholder/oauth2/callback"
    oidc_issuer_url="ISSUER_URL_PLACEHOLDER"
    ssl_insecure_skip_verify=true
    
    client_id="henkan-designer"
    client_secret="ozX1h8tTCm6N54zFAvyUBF2c1nduIoZe"
    cookie_secret="a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"
    cookie_secure="false"
    
    http_address="0.0.0.0:5000"
    upstreams="http://127.0.0.1:placeholder-port/"
    
    user_id_claim="preferred_username"
    skip_auth_routes=["/health.*"]
    skip_provider_button="true"
    reverse_proxy="true"
    
    cookie_domains=["placeholder-domain"]
    whitelist_domains=["placeholder-domain:*"]