apiVersion: theia.cloud/v1beta8
kind: Session
metadata:
  name: bartu-demo-ws
  namespace: default
  labels:
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
    app.henkan.io/henkanProjectName: bartu-demo-workspace
spec:
  name: bartu-demo-ws
  workspace: bartu-demo-ws
  appDefinition: henkan-designer
  user: bartu
  sessionSecret: henkansecret

  envVars:
    HENKAN_PROJECT_NAME: busra
    HENKAN_PROJECT_GIT_URL: https://github.com/GlobalMaksimum/henkan-etl-flow-project.git
    HENKAN_META_API_URL: http://henkan-metaapi.henkan-metaapi
    HENKAN_GIT_USER: bartu
    HENKAN_GIT_EMAIL: bartu.kacar@globalmaksimum.com
    EMAIL: bartu.kacar@globalmaksimum.com
    GIT_AUTHOR_NAME: bartu405
    GIT_SSL_NO_VERIFY: "true"
    COMMIT_GENAI_ENDPOINT: https://example.com/webhook/xyz

