apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2026-01-12T11:52:35Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: theia-workspace
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
    theia-cloud.io/workspace-name: bartu-demo-ws
    workspace-name: bartu-demo-ws
  name: ws-bartu-henkan-designer-e6585688027a
  namespace: default
  ownerReferences:
    - apiVersion: theia.cloud/v1beta5
      blockOwnerDeletion: true
      controller: true
      kind: Workspace
      name: bartu-demo-ws
      uid: cd5e9007-7f7c-48f6-b353-e6585688027a
  resourceVersion: "300394"
  uid: 28bd77dc-e2bf-44a8-913b-72187dd2085c
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-28bd77dc-e2bf-44a8-913b-72187dd2085c
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Mi
  phase: Bound