apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2026-01-12T12:27:41Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    theia-cloud.io/workspace-name: bartu-demo-ws
  name: ws-bartu-henkan-designer-073f4c011090
  namespace: default
  ownerReferences:
    - apiVersion: theia.cloud/v1beta5
      blockOwnerDeletion: true
      controller: true
      kind: Workspace
      name: bartu-demo-ws
      uid: 5af3a969-56ce-4575-901a-073f4c011090
  resourceVersion: "304083"
  uid: 4f7365d5-5799-4cab-92aa-bac843daaad1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-4f7365d5-5799-4cab-92aa-bac843daaad1
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Mi
  phase: Bound