apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2026-01-05T08:49:16Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: theia-workspace
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
    theia-cloud.io/workspace-name: bartu-demo-ws
    workspace-name: bartu-demo-ws
  name: ws-bartu-henkan-designer-efa6a4b2e790
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Workspace
      name: bartu-demo-ws
      uid: 49296f88-db8e-4182-a6df-efa6a4b2e790
  resourceVersion: "162937"
  uid: 63a6833b-6c82-44da-afb8-4a3753205d54
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-63a6833b-6c82-44da-afb8-4a3753205d54
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Mi
  phase: Bound