apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/proxy-body-size":"1m","nginx.ingress.kubernetes.io/proxy-buffer-size":"128k","nginx.ingress.kubernetes.io/rewrite-target":"/$2"},"name":"henkan-designer-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"theia.localtest.me"}]}}
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  creationTimestamp: "2026-01-06T11:38:30Z"
  generation: 4
  name: henkan-designer-ingress
  namespace: default
  ownerReferences:
    - apiVersion: theia.cloud/v1beta10
      kind: AppDefinition
      name: henkan-designer
      uid: 08201587-d9d5-4e2c-b794-65f57b9b39b4
  resourceVersion: "209216"
  uid: 292dd365-fbad-4356-b0d7-86653f4e980c
spec:
  ingressClassName: nginx
  rules:
    - host: theia.localtest.me
    - host: theia.localtest.me
    - host: theia.localtest.me
      http:
        paths:
          - backend:
              service:
                name: session-bartu-henkan-designer-38852e7b602c
                port:
                  number: 3000
            path: /dfb60967-ade1-4261-8ee9-38852e7b602c(/|$)(.*)
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 10.98.95.61