apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"example.suleyman.io/v1","kind":"Workspace","metadata":{"annotations":{},"labels":{"app.henkan.io/henkanProjectName":"bartu-demo-workspace","app.henkan.io/workspaceName":"demo-ws","app.henkan.io/workspaceUser":"bartu"},"name":"bartu-demo-ws","namespace":"default"},"spec":{"appDefinition":"henkan-designer","label":"bartu-demo-workspace","name":"bartu-demo-ws","user":"bartu"}}
  creationTimestamp: "2026-01-05T08:49:15Z"
  generation: 2
  labels:
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: AppDefinition
      name: henkan-designer
      uid: cb715568-1406-426f-a754-10a210f9539c
  resourceVersion: "162940"
  uid: 49296f88-db8e-4182-a6df-efa6a4b2e790
spec:
  appDefinition: henkan-designer
  label: bartu-demo-workspace
  name: bartu-demo-ws
  storage: ws-bartu-henkan-designer-efa6a4b2e790
  user: bartu
status:
  operatorMessage: PVC bound, finalizing workspace
  operatorStatus: HANDLING
  volumeAttach:
    message: PVC is bound
    status: claimed
  volumeClaim:
    message: ""
    status: finished