apiVersion: theia.cloud/v1beta10
kind: AppDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"theia.cloud/v1beta10","kind":"AppDefinition","metadata":{"annotations":{},"name":"henkan-designer","namespace":"default"},"spec":{"downlinkLimit":30000,"image":"ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest","imagePullPolicy":"IfNotPresent","ingressname":"henkan-designer-ingress","limitsCpu":"2","limitsMemory":"1200Mi","maxInstances":50,"minInstances":0,"mountPath":"/home/henkan/project","name":"henkan-designer","port":3000,"pullSecret":"regcred","requestsCpu":"100m","requestsMemory":"1000Mi","timeout":180,"uid":101,"uplinkLimit":30000}}
  creationTimestamp: "2026-01-12T11:52:34Z"
  generation: 1
  name: henkan-designer
  namespace: default
  resourceVersion: "300382"
  uid: 8e9d216d-798b-4604-9597-424a9b455266
spec:
  downlinkLimit: 30000
  image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest
  imagePullPolicy: IfNotPresent
  ingressname: henkan-designer-ingress
  limitsCpu: "2"
  limitsMemory: 1200Mi
  maxInstances: 50
  minInstances: 0
  mountPath: /home/henkan/project
  name: henkan-designer
  port: 3000
  pullSecret: regcred
  requestsCpu: 100m
  requestsMemory: 1000Mi
  timeout: 180
  uid: 101
  uplinkLimit: 30000
status:
  operatorMessage: AppDefinition handled
  operatorStatus: HANDLED