apiVersion: theia.cloud/v1beta5
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"theia.cloud/v1beta5","kind":"Workspace","metadata":{"annotations":{},"labels":{"app.henkan.io/henkanProjectName":"bartu-demo-workspace","app.henkan.io/workspaceName":"demo-ws","app.henkan.io/workspaceUser":"bartu"},"name":"bartu-demo-ws","namespace":"default"},"spec":{"appDefinition":"henkan-designer","label":"bartu-demo-workspace","name":"bartu-demo-ws","user":"bartu"}}
  creationTimestamp: "2026-01-12T12:14:42Z"
  generation: 2
  labels:
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
    - apiVersion: theia.cloud/v1beta10
      blockOwnerDeletion: true
      controller: true
      kind: AppDefinition
      name: henkan-designer
      uid: 8e9d216d-798b-4604-9597-424a9b455266
  resourceVersion: "302478"
  uid: 363bb9fa-229f-48c7-bd5e-6caf74ab7d8c
spec:
  appDefinition: henkan-designer
  label: bartu-demo-workspace
  name: bartu-demo-ws
  storage: ws-bartu-henkan-designer-6caf74ab7d8c
  user: bartu
status:
  operatorMessage: Workspace handled
  operatorStatus: HANDLED
  volumeAttach:
    message: ""
    status: finished
  volumeClaim:
    message: ""
    status: finished