apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  versions:
    - name: v1beta8
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                appDefinition:
                  pattern: ^[a-z0-9A-Z-_]+$
                  type: string
                envVars:
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                  type: object
                envVarsFromConfigMaps:
                  items:
                    type: string
                  type: array
                envVarsFromSecrets:
                  items:
                    type: string
                  type: array
                name:
                  pattern: ^[a-z0-9A-Z-_]+$
                  type: string
                options:
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                  type: object
                sessionSecret:
                  type: string
                user:
                  type: string
                workspace:
                  type: string
              required:
                - name
                - user
                - appDefinition
              type: object
            status:
              properties:
                error:
                  type: string
                lastActivity:
                  type: integer
                operatorMessage:
                  type: string
                operatorStatus:
                  type: string
                url:
                  type: string
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}