# File: session-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.theia.cloud
spec:
  group: theia.cloud
  scope: Namespaced
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  versions:
    - name: v1beta8
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [name, user, appDefinition]
              properties:
                name:
                  type: string
                  pattern: "^[a-z0-9A-Z-_]+$"
                user:
                  type: string
                appDefinition:
                  type: string
                  pattern: "^[a-z0-9A-Z-_]+$"
                workspace:
                  type: string
                sessionSecret:
                  type: string
                envVars:
                  type: object
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                envVarsFromConfigMaps:
                  type: array
                  items:
                    type: string
                envVarsFromSecrets:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                url:
                  type: string
                error:
                  type: string
                lastActivity:
                  type: integer
