# File: workspace-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.theia.cloud
spec:
  group: theia.cloud
  scope: Namespaced
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
    shortNames: [ws]
  versions:
    - name: v1beta5
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [name, user]
              properties:
                name:
                  type: string
                  pattern: "^[a-z0-9A-Z-_]+$"
                user:
                  type: string
                appDefinition:
                  type: string
                  pattern: "^[a-z0-9A-Z-_]+$"
                label:
                  type: string
                storage:
                  type: string
            status:
              type: object
              properties:
                operatorStatus:
                  type: string
                operatorMessage:
                  type: string
                error:
                  type: string
                volumeClaim:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                volumeAttach:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string