apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  namespace: default
  labels:
    app: operator
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: operator
    spec:
      automountServiceAccountToken: true
      serviceAccount: operator-api-service-account
      serviceAccountName: operator-api-service-account
      containers:
        - name: operator-container
          image: my-operator:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - --keycloak
            - --keycloakURL
            - http://192.168.19.247:8080/auth/
            - --keycloakRealm
            - henkan
            - --keycloakClientId
            - henkan-designer
            - --instancesHost
            - theia.localtest.me
            - --appId
            - henkan
            - --storageClassName
            - hostpath
            - --requestedStorage
            - 250Mi
            - --oAuth2ProxyVersion
            - quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30