## File: oauth2-configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: theia-oauth2-proxy-config
  namespace: default
data:
  oauth2-proxy.cfg: |
    # TODO real config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-templates
  namespace: default
data:
  dummy: "template"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: theia-oauth2-emails
  namespace: default
data:
  authenticated-emails-list: "*"
