apiVersion: example.suleyman.io/v1
kind: AppDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"example.suleyman.io/v1","kind":"AppDefinition","metadata":{"annotations":{},"name":"sample-app","namespace":"default"},"spec":{"downlinkLimit":30000,"image":"ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest","imagePullPolicy":"IfNotPresent","ingressname":"sample-app-ingress","limitsCpu":"2","limitsMemory":"1200Mi","maxInstances":50,"minInstances":0,"mountPath":"/home/henkan/project","name":"sample-app","port":3000,"pullSecret":"regcred","requestsCpu":"100m","requestsMemory":"1000Mi","timeout":180,"uid":101,"uplinkLimit":30000}}
  creationTimestamp: "2025-12-18T10:42:07Z"
  generation: 1
  name: sample-app
  namespace: default
  resourceVersion: "1933843"
  uid: 012aebb0-f89a-42cd-9e6c-5045c6d095de
spec:
  downlinkLimit: 30000
  image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:latest
  imagePullPolicy: IfNotPresent
  ingressname: sample-app-ingress
  limitsCpu: "2"
  limitsMemory: 1200Mi
  maxInstances: 50
  minInstances: 0
  mountPath: /home/henkan/project
  name: sample-app
  port: 3000
  pullSecret: regcred
  requestsCpu: 100m
  requestsMemory: 1000Mi
  timeout: 180
  uid: 101
  uplinkLimit: 30000
status:
  operatorMessage: AppDefinition handled
  operatorStatus: HANDLED