apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2025-12-17T12:53:17Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: theia-workspace
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
    theia-cloud.io/workspace-name: bartu-demo-ws
    workspace-name: bartu-demo-ws
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Workspace
      name: bartu-demo-ws
      uid: c4ed3ad0-1228-4c1c-a3c4-54d3f6c39124
  resourceVersion: "1875719"
  uid: 9f896ffc-cd4e-4d49-9d62-d394bbda4ff2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-9f896ffc-cd4e-4d49-9d62-d394bbda4ff2
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound