apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/proxy-body-size":"1m","nginx.ingress.kubernetes.io/proxy-buffer-size":"128k","nginx.ingress.kubernetes.io/rewrite-target":"/$2","nginx.ingress.kubernetes.io/use-regex":"true"},"name":"sample-app-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"theia.localtest.me"}]}}
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2025-12-18T10:42:07Z"
  generation: 7
  name: sample-app-ingress
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      kind: AppDefinition
      name: sample-app
      uid: 012aebb0-f89a-42cd-9e6c-5045c6d095de
  resourceVersion: "1936980"
  uid: 186878fd-9d33-49e7-bf48-b253417be1f9
spec:
  ingressClassName: nginx
  rules:
    - host: theia.localtest.me
status:
  loadBalancer: {}