apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2025-12-17T12:53:18Z"
  generation: 1
  labels:
    app: theia
  name: sample-app
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: AppDefinition
      name: sample-app
      uid: 5c501d79-c334-4fc3-8373-119471b852b9
  resourceVersion: "1875741"
  uid: 0cba3086-a5c7-46c3-8754-471f340a23a1
spec:
  rules:
    - host: theia.localtest.me
      http:
        paths:
          - backend:
              service:
                name: theia-bartu-demo-ws
                port:
                  name: http
            path: /e69e7867-60d9-4ec7-bbb5-900d2d438e2e/
            pathType: Prefix
status:
  loadBalancer: {}