apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2026-01-03T12:37:14Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: theia-workspace
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
    theia-cloud.io/workspace-name: bartu-demo-ws
    workspace-name: bartu-demo-ws
  name: ws-bartu-sample-app-604486568146
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Workspace
      name: bartu-demo-ws
      uid: 9927ed86-9801-4c7e-a7e7-604486568146
  resourceVersion: "128316"
  uid: 82e7d3df-3ae9-4e31-a674-1d8bea7bd42b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-82e7d3df-3ae9-4e31-a674-1d8bea7bd42b
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Mi
  phase: Bound