apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/proxy-body-size":"1m","nginx.ingress.kubernetes.io/proxy-buffer-size":"128k","nginx.ingress.kubernetes.io/rewrite-target":"/$2","nginx.ingress.kubernetes.io/use-regex":"true"},"name":"sample-app-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"theia.localtest.me"}]}}
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2026-01-04T07:49:34Z"
  generation: 2
  name: sample-app-ingress
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      kind: AppDefinition
      name: sample-app
      uid: 1a99e47e-9c4c-4d0a-aa4d-d87c37bb9741
  resourceVersion: "133185"
  uid: 0bb526c0-2f77-467a-8c32-dc83786ad0e9
spec:
  ingressClassName: nginx
  rules:
    - host: theia.localtest.me
    - host: theia.localtest.me
      http:
        paths:
          - backend:
              service:
                name: session-bartu-sample-app-e6ece5b6f290
                port:
                  number: 3000
            path: /a0e8af80-626a-4285-b152-e6ece5b6f290(/|$)(.*)
            pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
      - ip: 10.98.95.61