apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"example.suleyman.io/v1","kind":"Workspace","metadata":{"annotations":{},"labels":{"app.henkan.io/henkanProjectName":"bartu-demo-workspace","app.henkan.io/workspaceName":"demo-ws","app.henkan.io/workspaceUser":"bartu"},"name":"bartu-demo-ws","namespace":"default"},"spec":{"appDefinition":"sample-app","label":"bartu-demo-workspace","name":"bartu-demo-ws","user":"bartu"}}
  creationTimestamp: "2025-12-18T10:42:08Z"
  generation: 2
  labels:
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: AppDefinition
      name: sample-app
      uid: 012aebb0-f89a-42cd-9e6c-5045c6d095de
  resourceVersion: "1933848"
  uid: af5f73a0-6d79-4b65-b238-4b516cb28f2f
spec:
  appDefinition: sample-app
  label: bartu-demo-workspace
  name: bartu-demo-ws
  storage: ws-storage-bartu-demo-ws
  user: bartu
status:
  operatorMessage: Workspace reconciled successfully
  operatorStatus: HANDLED
  volumeAttach:
    message: ""
    status: finished
  volumeClaim:
    message: ""
    status: finished