apiVersion: example.suleyman.io/v1
kind: Workspace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"example.suleyman.io/v1","kind":"Workspace","metadata":{"annotations":{},"labels":{"app.henkan.io/henkanProjectName":"bartu-demo-workspace","app.henkan.io/workspaceName":"demo-ws","app.henkan.io/workspaceUser":"bartu"},"name":"bartu-demo-ws","namespace":"default"},"spec":{"appDefinition":"sample-app","label":"bartu-demo-workspace","name":"bartu-demo-ws","user":"bartu"}}
  creationTimestamp: "2026-01-03T12:37:14Z"
  generation: 2
  labels:
    app.henkan.io/henkanProjectName: bartu-demo-workspace
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
  name: bartu-demo-ws
  namespace: default
  ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: AppDefinition
      name: sample-app
      uid: 9085f464-8fce-4032-bdd7-fe420360e8fb
  resourceVersion: "128356"
  uid: 9927ed86-9801-4c7e-a7e7-604486568146
spec:
  appDefinition: sample-app
  label: bartu-demo-workspace
  name: bartu-demo-ws
  storage: ws-bartu-sample-app-604486568146
  user: bartu
status:
  operatorMessage: PVC bound, finalizing workspace
  operatorStatus: HANDLING
  volumeAttach:
    message: PVC is bound
    status: claimed
  volumeClaim:
    message: ""
    status: finished