apiVersion: theia.cloud/v1beta10
kind: AppDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"theia.cloud/v1beta9","kind":"AppDefinition","metadata":{"name":"henkan-designer","namespace":"henkan-designer"},"spec":{"downlinkLimit":30000,"image":"henkan.azurecr.io/globalmaksimum/theia-henkan:v2.3.3","imagePullPolicy":"IfNotPresent","ingressname":"theia-cloud-demo-ws-ingress","limitsCpu":"2","limitsMemory":"1200M","maxInstances":50,"minInstances":0,"mountPath":"/home/henkan/project","name":"henkan-designer","port":3000,"pullSecret":"regcred","requestsCpu":"100m","requestsMemory":"1000M","timeout":180,"uid":101,"uplinkLimit":30000}}'
  creationTimestamp: "2025-12-04T12:26:51Z"
  generation: 1
  name: henkan-designer
  namespace: henkan-designer
  resourceVersion: "67781754"
  uid: 809b363f-067f-4d38-a79f-52b699f5080e
spec:
  downlinkLimit: 30000
  image: henkan.azurecr.io/globalmaksimum/theia-henkan:v2.3.3
  imagePullPolicy: IfNotPresent
  ingressname: theia-cloud-demo-ws-ingress
  limitsCpu: "2"
  limitsMemory: 1200M
  maxInstances: 50
  minInstances: 0
  mountPath: /home/henkan/project
  name: henkan-designer
  port: 3000
  pullSecret: regcred
  requestsCpu: 100m
  requestsMemory: 1000M
  timeout: 180
  uid: 101
  uplinkLimit: 30000
status:
  operatorStatus: HANDLED