apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appdefinitions.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: AppDefinition
    listKind: AppDefinitionList
    plural: appdefinitions
    shortNames:
      - appdef
      - ad
    singular: appdefinition
  scope: Namespaced
  versions:
    - name: v1beta10
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                downlinkLimit:
                  type: integer
                image:
                  type: string
                imagePullPolicy:
                  enum:
                    - Always
                    - IfNotPresent
                    - Never
                  type: string
                ingressname:
                  type: string
                limitsCpu:
                  type: string
                limitsMemory:
                  type: string
                maxInstances:
                  type: integer
                minInstances:
                  type: integer
                monitor:
                  properties:
                    activityTracker:
                      properties:
                        notifyAfter:
                          type: integer
                        timeoutAfter:
                          type: integer
                      type: object
                    port:
                      type: integer
                  type: object
                mountPath:
                  type: string
                name:
                  pattern: ^[a-z0-9A-Z-_]+$
                  type: string
                options:
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                  type: object
                port:
                  maximum: 65535
                  minimum: 0
                  type: integer
                pullSecret:
                  type: string
                requestsCpu:
                  type: string
                requestsMemory:
                  type: string
                timeout:
                  type: integer
                uid:
                  type: integer
                uplinkLimit:
                  type: integer
              required:
                - name
                - image
                - uid
                - port
                - ingressname
                - minInstances
                - maxInstances
                - requestsCpu
                - requestsMemory
                - limitsMemory
                - limitsCpu
              type: object
              x-kubernetes-validations:
                - message: minInstances should be less or equal than maxInstances.
                  rule: self.minInstances <= self.maxInstances
            status:
              properties:
                operatorMessage:
                  type: string
                operatorStatus:
                  type: string
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}