apiVersion: v1
data:
  authenticated-emails-list: bartu
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-12T11:52:35Z"
  labels:
    app.kubernetes.io/component: session
    app.kubernetes.io/part-of: theia-cloud
    theia-cloud.io/app-definition: henkan-designer
    theia-cloud.io/session: bartu-demo-ws
    theia-cloud.io/template-purpose: emails
    theia-cloud.io/user: bartu
  name: session-email-bartu-henkan-desi-30611b8f5917
  namespace: default
  ownerReferences:
    - apiVersion: theia.cloud/v1beta8
      blockOwnerDeletion: true
      controller: true
      kind: Session
      name: bartu-demo-ws
      uid: 95474d16-0681-4f99-9d65-30611b8f5917
  resourceVersion: "300399"
  uid: c1953a48-736c-484f-b5cf-2619d15a9fc6