apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/proxy-body-size":"1m","nginx.ingress.kubernetes.io/proxy-buffer-size":"128k","nginx.ingress.kubernetes.io/rewrite-target":"/$2","nginx.ingress.kubernetes.io/use-regex":"true"},"name":"sample-app-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"theia.localtest.me"}]}}
      nginx.ingress.kubernetes.io/proxy-body-size: 1m
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    creationTimestamp: "2026-01-02T11:18:35Z"
    generation: 2
    name: sample-app-ingress
    namespace: default
    ownerReferences:
    - apiVersion: example.suleyman.io/v1
      kind: AppDefinition
      name: sample-app
      uid: 37c85fd8-8215-46ad-bc44-011756fde05f
    resourceVersion: "105596"
    uid: 7dfe4f3a-967e-476d-8bc6-bf4385b3a727
  spec:
    ingressClassName: nginx
    rules:
    - host: theia.localtest.me
      http:
        paths:
        - backend:
            service:
              name: session-bartu-sample-app-43cf67a945e3
              port:
                number: 3000
          path: /96aff083-e1a9-4a76-b51f-43cf67a945e3(/|$)(.*)
          pathType: ImplementationSpecific
  status:
    loadBalancer:
      ingress:
      - ip: 10.98.95.61
kind: List
metadata:
  resourceVersion: ""
