apiVersion: v1
items:
- apiVersion: v1
  data:
    authenticated-emails-list: bartu
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-01-02T11:18:36Z"
    labels:
      app.kubernetes.io/component: session
      app.kubernetes.io/part-of: theia-cloud
      theia-cloud.io/app-definition: sample-app
      theia-cloud.io/session: bartu-demo-ws
      theia-cloud.io/template-purpose: emails
      theia-cloud.io/user: bartu
    name: session-email-bartu-sample-app-43cf67a945e3
    namespace: default
    ownerReferences:
    - apiVersion: example.suleyman.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Session
      name: bartu-demo-ws
      uid: 96aff083-e1a9-4a76-b51f-43cf67a945e3
    resourceVersion: "105489"
    uid: 4d4c0988-7f58-4b85-ba06-e70cef3f268a
kind: List
metadata:
  resourceVersion: ""
