apiVersion: theia.cloud/v1beta5
kind: Workspace
metadata:
  name: bartu-demo-ws
  namespace: default
  labels:
    app.henkan.io/workspaceName: demo-ws
    app.henkan.io/workspaceUser: bartu
    app.henkan.io/henkanProjectName: bartu-demo-workspace
spec:
  name: bartu-demo-ws
  label: bartu-demo-workspace
  appDefinition: henkan-designer
  user: bartu