apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"appdefinitions.theia.cloud"},"spec":{"group":"theia.cloud","names":{"kind":"AppDefinition","listKind":"AppDefinitionList","plural":"appdefinitions","shortNames":["appdef","ad"],"singular":"appdefinition"},"scope":"Namespaced","versions":[{"name":"v1beta10","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"downlinkLimit":{"type":"integer"},"image":{"type":"string"},"imagePullPolicy":{"enum":["Always","IfNotPresent","Never"],"type":"string"},"ingressname":{"type":"string"},"limitsCpu":{"type":"string"},"limitsMemory":{"type":"string"},"maxInstances":{"type":"integer"},"minInstances":{"type":"integer"},"monitor":{"properties":{"activityTracker":{"properties":{"notifyAfter":{"type":"integer"},"timeoutAfter":{"type":"integer"}},"type":"object"},"port":{"type":"integer"}},"type":"object"},"mountPath":{"type":"string"},"name":{"pattern":"^[a-z0-9A-Z-_]+$","type":"string"},"port":{"maximum":65535,"minimum":0,"type":"integer"},"pullSecret":{"type":"string"},"requestsCpu":{"type":"string"},"requestsMemory":{"type":"string"},"timeout":{"type":"integer"},"uid":{"type":"integer"},"uplinkLimit":{"type":"integer"}},"required":["name","image","uid","port","ingressname","minInstances","maxInstances","requestsCpu","requestsMemory","limitsMemory","limitsCpu"],"type":"object","x-kubernetes-validations":[{"message":"minInstances should be less or equal than maxInstances.","rule":"self.minInstances \u003c= self.maxInstances"}]},"status":{"properties":{"operatorMessage":{"type":"string"},"operatorStatus":{"type":"string"}},"type":"object"}},"required":["spec"],"type":"object"}},"served":true,"storage":true,"subresources":{"status":{}}}]}}
  creationTimestamp: "2026-01-06T11:30:21Z"
  generation: 1
  name: appdefinitions.theia.cloud
  resourceVersion: "204053"
  uid: 1167ff07-a0e4-4bd6-8475-9bde6f8aef4f
spec:
  conversion:
    strategy: None
  group: theia.cloud
  names:
    kind: AppDefinition
    listKind: AppDefinitionList
    plural: appdefinitions
    shortNames:
      - appdef
      - ad
    singular: appdefinition
  scope: Namespaced
  versions:
    - name: v1beta10
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                downlinkLimit:
                  type: integer
                image:
                  type: string
                imagePullPolicy:
                  enum:
                    - Always
                    - IfNotPresent
                    - Never
                  type: string
                ingressname:
                  type: string
                limitsCpu:
                  type: string
                limitsMemory:
                  type: string
                maxInstances:
                  type: integer
                minInstances:
                  type: integer
                monitor:
                  properties:
                    activityTracker:
                      properties:
                        notifyAfter:
                          type: integer
                        timeoutAfter:
                          type: integer
                      type: object
                    port:
                      type: integer
                  type: object
                mountPath:
                  type: string
                name:
                  pattern: ^[a-z0-9A-Z-_]+$
                  type: string
                port:
                  maximum: 65535
                  minimum: 0
                  type: integer
                pullSecret:
                  type: string
                requestsCpu:
                  type: string
                requestsMemory:
                  type: string
                timeout:
                  type: integer
                uid:
                  type: integer
                uplinkLimit:
                  type: integer
              required:
                - name
                - image
                - uid
                - port
                - ingressname
                - minInstances
                - maxInstances
                - requestsCpu
                - requestsMemory
                - limitsMemory
                - limitsCpu
              type: object
              x-kubernetes-validations:
                - message: minInstances should be less or equal than maxInstances.
                  rule: self.minInstances <= self.maxInstances
            status:
              properties:
                operatorMessage:
                  type: string
                operatorStatus:
                  type: string
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: AppDefinition
    listKind: AppDefinitionList
    plural: appdefinitions
    shortNames:
      - appdef
      - ad
    singular: appdefinition
  conditions:
    - lastTransitionTime: "2026-01-06T11:30:21Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2026-01-06T11:30:21Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1beta10