apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"workspaces.theia.cloud"},"spec":{"group":"theia.cloud","names":{"kind":"Workspace","listKind":"WorkspaceList","plural":"workspaces","shortNames":["ws"],"singular":"workspace"},"scope":"Namespaced","versions":[{"name":"v1beta5","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"appDefinition":{"pattern":"^[a-z0-9A-Z-_]+$","type":"string"},"label":{"type":"string"},"name":{"pattern":"^[a-z0-9A-Z-_]+$","type":"string"},"options":{"additionalProperties":{"x-kubernetes-int-or-string":true},"type":"object"},"storage":{"type":"string"},"user":{"type":"string"}},"required":["name","user"],"type":"object"},"status":{"properties":{"error":{"type":"string"},"operatorMessage":{"type":"string"},"operatorStatus":{"type":"string"},"volumeAttach":{"properties":{"message":{"type":"string"},"status":{"type":"string"}},"type":"object"},"volumeClaim":{"properties":{"message":{"type":"string"},"status":{"type":"string"}},"type":"object"}},"type":"object"}},"required":["spec"],"type":"object"}},"served":true,"storage":true,"subresources":{"status":{}}}]}}
  creationTimestamp: "2026-01-06T11:30:21Z"
  generation: 2
  name: workspaces.theia.cloud
  resourceVersion: "208603"
  uid: 316a278f-0dc5-4431-91e6-e4e5acc61a97
spec:
  conversion:
    strategy: None
  group: theia.cloud
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    shortNames:
      - ws
    singular: workspace
  scope: Namespaced
  versions:
    - name: v1beta5
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                appDefinition:
                  pattern: ^[a-z0-9A-Z-_]+$
                  type: string
                label:
                  type: string
                name:
                  pattern: ^[a-z0-9A-Z-_]+$
                  type: string
                options:
                  additionalProperties:
                    x-kubernetes-int-or-string: true
                  type: object
                storage:
                  type: string
                user:
                  type: string
              required:
                - name
                - user
              type: object
            status:
              properties:
                error:
                  type: string
                operatorMessage:
                  type: string
                operatorStatus:
                  type: string
                volumeAttach:
                  properties:
                    message:
                      type: string
                    status:
                      type: string
                  type: object
                volumeClaim:
                  properties:
                    message:
                      type: string
                    status:
                      type: string
                  type: object
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    shortNames:
      - ws
    singular: workspace
  conditions:
    - lastTransitionTime: "2026-01-06T11:30:21Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2026-01-06T11:30:21Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1beta5